server:
  port: 8080
  shutdown: graceful

spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      refund: com.demo.refund
      payment: com.demo.payment
    consumer:
      group-id:
        refund: com.demo.refund
        payment: com.demo.payment